In [1]:
import pandas as pd

In [4]:
URL = "./data/KDS-S3-StockTrade-1-2024-09-30-17-53-33-dc45bdaa-56b2-4ce8-97cf-a21bbfd877ec.json"

In [5]:
df = pd.read_json(URL, lines=True)

In [6]:
df

    tickerSymbol tradeType   price  quantity   id
0            CVX       BUY   90.23       796    1
1             KO      SELL   47.02      4056    2
2            DIS      SELL   84.70      2546    3
3            XOM      SELL  105.90      4444    4
4            BUD       BUY  131.72      5223    5
..           ...       ...     ...       ...  ...
102          JPM       BUY   50.15      7475  103
103          PTR       BUY   92.67      5138  104
104           PG      SELL   98.77      9062  105
105          JNJ      SELL   90.76       515  106
106         GOOG       BUY  445.05      9631  107

[107 rows x 5 columns]

In [7]:
df.shape

(107, 5)

In [8]:
df.head(20)

   tickerSymbol tradeType   price  quantity  id
0           CVX       BUY   90.23       796   1
1            KO      SELL   47.02      4056   2
2           DIS      SELL   84.70      2546   3
3           XOM      SELL  105.90      4444   4
4           BUD       BUY  131.72      5223   5
5          AAPL       BUY  133.08      2011   6
6            KO       BUY   45.55      5456   7
7           WFC       BUY   47.40      2363   8
8           WFC       BUY   49.26      8886   9
9         RDS.A      SELL   58.58      4882  10
10            T       BUY   38.13      1880  11
11          PFE       BUY   28.92       783  12
12          JPM      SELL   47.67      3648  13
13        RDS.A       BUY   76.26      1302  14
14           FB      SELL   60.39      2247  15
15          NVS      SELL  110.68      5100  16
16          NVS       BUY  112.73      9621  17
17          DIS      SELL  107.12      5457  18
18          PFE       BUY   37.96      6811  19
19          NVS       BUY  120.65      6072  20